### ISSUE TITLE
DWT not build on windows with dmd  v2.076

### ISSUE THREAD

**Issue by dangbinghoo** [d-widget-toolkit/dwt#29]
$ dmd -run build.d base swt
Building dwt-base
workdir=>D:\NewDevel\dwt\base\src
java\nonstandard\RuntimeTraits.d(61): Error: undefined identifier `TypeInfo_Typedef`

object.Exception@build.d(256): compile error
----------------
0x0040595A
0x00406E24
0x00421063
0x00421027
0x00420F28
0x0041871F
0x752033AA in BaseThreadInitThunk
0x77169F72 in RtlInitializeExceptionChain
0x77169F45 in RtlInitializeExceptionChain
(in D:\NewDevel\dwt)
dmd.exe @D:\NewDevel\dwt\rsp

$ dmd --version
DMD32 D Compiler v2.076.0
Copyright (c) 1999-2017 by Digital Mars written by Walter Bright

I did the building in a git bash shell for windows. and dmd compiler bin path is in system's PATH env. var. settings.

I don't know why the build.d seems considered my Dlang compiler is not D2.

**Comment by menjaraz** [comment]
I managed to build the [DUB package for the D Widget Toolkit](https://github.com/jasc2v8/dwtlib) by deleting few lines of code (61 till 65) using DMD32 D Compiler v2.076.0 on my box.

I suspect `TypeInfo_Typedef` has to do with Tango...

**Comment by trikko** [comment]
Same on linux
