### ISSUE TITLE
Build fails with dmd 2.079 beta

### ISSUE THREAD

**Issue by schlupa** [d-widget-toolkit/dwt#37]
Just FYI, dwt building fails completely with dmd 2.079. Under windows it returns following output

> $ dub
Performing "debug" build using C:\pgm\D\dmd2\windows\bin\dmd.exe for x86.
dwt 1.0.0+swt-3.4.1: building configuration "windows-win32"...
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\gdip\Gdip.d(478,26): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\widgets\IME.d(506,40): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.
base\src\java\lang\String.d(413,23): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.
base\src\java\lang\String.d(414,23): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.
base\src\java\lang\String.d(429,23): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.
base\src\java\lang\String.d(430,23): Deprecation: The delete keyword has been deprecated.  Use object.destroy() instead.
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15427,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_ANALYSIS.eScript(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15419,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15428,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_ANALYSIS.fRTL(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15420,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15429,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_ANALYSIS.fLayoutRTL(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15421,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15430,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_ANALYSIS.fLinkBefore(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15422,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15431,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_ANALYSIS.fLinkAfter(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15423,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15432,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_ANALYSIS.fLogicalOrder(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15424,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15433,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_ANALYSIS.fNoGlyphIndex(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15425,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15454,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fContextDigits(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15445,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15455,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fInvertPreBoundDir(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15446,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15456,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fInvertPostBoundDir(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15447,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15457,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fLinkStringBefore(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15448,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15458,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fLinkStringAfter(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15449,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15459,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fNeutralOverride(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15450,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15460,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fNumericOverride(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15451,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15461,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_CONTROL.fLegacyBidiClass(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15452,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15490,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_LOGATTR.fSoftBreak(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15483,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15491,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_LOGATTR.fWhiteSpace(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15484,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15492,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_LOGATTR.fCharStop(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15485,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15493,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_LOGATTR.fWordStop(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15486,10)
org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15494,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_LOGATTR.fInvalid(uint val) cannot be overloaded with another extern(Windows) function at org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15487,10)
C:\pgm\D\dmd2\windows\bin\dmd.exe failed with exit code 1.

schlupa@D02DI1253808DGT MSYS /c/D/dwt (master)
$ dmd --version
DMD32 D Compiler v2.079.0-beta.1

Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

**Comment by jacob-carlborg** [comment]
It's a regression in the compiler. https://issues.dlang.org/show_bug.cgi?id=18385

**Comment by jacob-carlborg** [comment]
Works with the final release of 2.079.0.
